### PR TITLE
Merge latest facebook code including stereo audio generation 

### PR DESCRIPTION
**Pull request by adricl**
This might have issues around the models that don't exist in this HG account https://huggingface.co/GrandaddyShmax. For the stereo ones that might need to be copied across or changed to use the Facebook ones.

### CODE REVIEW

**Comment by yocontra** [comment]
@GrandaddyShmax Anything I can help with to get this over the finish line?

**Comment by GrandaddyShmax** [comment]
@yocontra Sadly I am currently unable to test it in order to implement it in the main branch. I can however create additional branch for this, and maybe for every code contributed by the community, there others would be able to test it out and see if that does not cause any unforeseen problems. Sounds good?

**Comment by matthoffner** [comment]
Thanks @adricl I threw your branch up to HuggingFace and verified it works: https://huggingface.co/spaces/matthoffner/AudioCraft_Plus_Latest

**Comment by adricl** [comment]
Thanks @matthoffner, I have verified it does work on my machine locally, "Works on my machine". I have not tried it on Huggingface so, thanks for that!

@GrandaddyShmax I was wondering with the models on your HuggingFace account, did you do any modifications or are they the same as the Facebook ones? 

There are a few stereo models that are very interesting that you don't have on your HuggingFace so I was wondering if we should fall back to Facebook or something. 

@GrandaddyShmax A new branch is fine.  

I also investigated the new model types and from what I can tell it does not allow for continuation so we cant use it for making music longer than 30 seconds.

**Comment by GrandaddyShmax** [comment]
@adricl I simply copied the models from Facebook huggingface back when they had issues there. No changes were made to the models.

I've made the `community` branch so you can pull request there until I'll be able to properly check them myself

**Comment by matthoffner** [comment]
I've verified the stereo models work by updating the code to point to the Facebook HuggingFace ones. The new Magnet ones seem to require more work.

**Comment by adricl** [comment]
I will close this now as I have merged to #69 for the Community branch.

**Pull request closed without merging**
